name: Run Insights API tests on prod env that check business countries in a row (only tests that fit load testing)
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  tests:
    name: Run INSIGHTS API tests
    timeout-minutes: 26
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: "prod"
      SLACK_BOT_USER_OAUTH_TOKEN: ${{secrets.PLAYWRIGHT_TOKEN }}
      IS_TESTING_BUSINESS_COUNTRIES_IN_A_ROW_AT_INSIGHTS_API: true
      TYPE: "insights"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Create .env file
        shell: bash
        run: |
          rm -rf .env.playwright
          echo "SLACK_BOT_USER_OAUTH_TOKEN=${SLACK_BOT_USER_OAUTH_TOKEN}" >> .env.playwright
          echo "ENVIRONMENT=$ENVIRONMENT" >> .env.playwright
          echo "IS_TESTING_BUSINESS_COUNTRIES_IN_A_ROW_AT_INSIGHTS_API=$IS_TESTING_BUSINESS_COUNTRIES_IN_A_ROW_AT_INSIGHTS_API" >> .env.playwright
          echo "TYPE=${TYPE}" >> .env.playwright
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: playwright-cache
        with:
          path: |
            ~/.npm
            ~/.cache/ms-playwright/
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}
            ${{ runner.os }}-

      - name: Update playwright and install dependencies
        shell: bash
        run: |
          pnpm add -g playwright@latest
          pnpm add -D @playwright/test@latest
          npx playwright install --with-deps

      - name: Download previously checked countries list
        uses: actions/download-artifact@v4
        with:
          name: countries-for-workflow
        continue-on-error: true

      - name: Run INSIGHTS API tests
        run: npx playwright test --project=insights_api_tests --grep @fitsLoadTesting

      - name: Upload checked countries list
        uses: actions/upload-artifact@v4
        with:
          name: countries-for-workflow
          path: tests/tests-data/lookup-data/countries-for-workflow.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
