name: Run load event api tests on prod env
run-name: Run '${{ github.event.inputs.what_to_test }}' tests on prod env

on:
  workflow_dispatch:
    inputs:
      what_to_test:
        type: choice
        required: true
        options:
          - search events by areas
          - get events by ids (for all events at feed)
          - get observations by ids (for all events at feed)
        description: |
          Which tests to run
      feed:
        type: string
        required: true
        description: |
          Feed to test on. Example: kontur-private
      types:
        type: string
        required: true
        description: |
          Types to test on, devided by comma. Example: FLOOD, WILDFIRE, EARTHQUAKE, CYCLONE, STORM
      episode_filter_type:
        type: choice
        required: true
        options:
          - ANY
          - NONE
          - LATEST
        description: |
          Episode filter type to test on. Example: LATEST
      numbers_of_requests:
        type: number
        required: true
        description: |
          First describe the number of parallel requests to run in a bunch of requests and then whole number of requests (used at search events test only). Devide with slash. Example: 100/1000
      limit:
        type: number
        required: true
        description: |
          Limit for the number of events to get. Example: 1000
      token:
        type: string
        required: true
        description: |
          Token to use for the requests. Get it after login to platform from keycloak.
      pause_between_banches_of_requests:
        type: number
        required: true
        description: |
          Pause between bunches of requests in ms. Example: 1000. Set to 0 not to make a pause between bunches of requests.
      bbox_shift_step:
        type: string
        required: false
        description: |
          Bbox to start requesting at search events test, devided by comma. Then describe a shift step for the bbox on search events test to move the bbox on each request. Devide with slash. Example: -93.2175, 30.198, -93.2165, 30.199 / 0.00001
      after:
        type: string
        required: false
        description: |
          After date to start requesting at search events test, in ISO format. Example: 2024-02-13T23:20:50.52Z
jobs:
  load-test:
    name: Run load event api tests
    runs-on: ubuntu-latest
    env:
      FEED: ${{ github.event.inputs.feed }}
      TYPES: ${{ github.event.inputs.types }}
      EPISODE_FILTER_TYPE: ${{ github.event.inputs.episode_filter_type }}
      LIMIT: ${{ github.event.inputs.limit }}
      TOKEN: ${{ github.event.inputs.token }}
      PAUSE_BETWEEN_BANCHES_OF_REQUESTS: ${{ github.event.inputs.pause_between_banches_of_requests }}
      AFTER: ${{ github.event.inputs.after }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.6.0"
      - name: Install packages
        run: npm install
      - name: Create .env file
        shell: bash
        run: |
          rm -rf .env.event-api-stress
          echo "FEED=$FEED" >> .env.event-api-stress
          echo "TYPES=$TYPES" >> .env.event-api-stress
          echo "EPISODE_FILTER_TYPE=$EPISODE_FILTER_TYPE" >> .env.event-api-stress
          echo "NUMBER_OF_PARALLEL_REQUESTS=$(echo '${{ github.event.inputs.numbers_of_requests }}' | cut -d '/' -f 1)" >> .env.event-api-stress
          echo "NUMBER_OF_REQUESTS=$(echo '${{ github.event.inputs.numbers_of_requests }}' | cut -d '/' -f 2)" >> .env.event-api-stress
          echo "LIMIT=$LIMIT" >> .env.event-api-stress
          echo "TOKEN=$TOKEN" >> .env.event-api-stress
          echo "PAUSE_BETWEEN_BANCHES_OF_REQUESTS=$PAUSE_BETWEEN_BANCHES_OF_REQUESTS" >> .env.event-api-stress
          echo "AFTER=$AFTER" >> .env.event-api-stress
          echo "BBOX=$(echo '${{ github.event.inputs.bbox_shift_step }}' | cut -d '/' -f 1)" >> .env.event-api-stress
          echo "SHIFTSTEP=$(echo '${{ github.event.inputs.bbox_shift_step }}' | cut -d '/' -f 2)" >> .env.event-api-stress

      - name: Run search events tests
        if: ${{ github.event.inputs.what_to_test == 'search events by areas'}}
        run: |
          cd stress-tests/event-api
          node --experimental-strip-types searchEventsTest.ts
      - name: Run get events by ids tests
        if: ${{ github.event.inputs.what_to_test == 'get events by ids (for all events at feed)'}}
        run: |
          cd stress-tests/event-api
          node --experimental-strip-types returnEventsTest.ts
      - name: Run get observations by ids tests
        if: ${{ github.event.inputs.what_to_test == 'get observations by ids (for all events at feed)'}}
        run: |
          cd stress-tests/event-api
          node --experimental-strip-types returnObservationsTest.ts
      - name: Read results analytics
        if: ${{ success() }}
        run: |
          cd stress-tests/event-api
          MESSAGE=$(cat analytics.txt)
          echo "message<<EOF" >> $GITHUB_ENV
          echo "$MESSAGE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Send message to Slack
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.PLAYWRIGHT_TOKEN  }}
          payload: |
            channel: ${{ secrets.EVENT_API_CHANNEL_ID }}
            text: ${{ env.MESSAGE }}
      - name: Upload tests results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: load-event-api-analytics
          path: stress-tests/event-api/analytics.txt
          retention-days: 30
