name: Run front-facing API tests
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        options:
          - dev
          - test
          - prod
      app:
        type: choice
        required: true
        default: all
        options:
          - atlas
          - disaster-ninja
          - smart-city
          - oam
          - all
jobs:
  tests:
    name: Run front-facing API tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: playwright-cache
        with:
          path: |
            ~/.npm
            ~/.cache/ms-playwright/
          key: ${{ runner.os }}-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}
            ${{ runner.os }}-

      - name: Update playwright and install dependencies
        shell: bash
        run: |
          pnpm add -g playwright@latest
          pnpm add -D @playwright/test@latest
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --trace on

      - name: Upload tests results
        uses: actions/upload-artifact@v4
        if: !cancelled()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
